name: push_hava_a_test
on:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: '0 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push_hava_a_test
        run: |
          /bin/bash push_hava_a_test.sh
        